### ISSUE TITLE
Add environment variable for local versus cloud deployments

### ISSUE THREAD

**Issue by lypht** [heptio/java-prototype#39]
Our jdbc string should allow for variable injection at runtime so that we can use one image for multiple environments.

In values.yaml:
```yaml
localDevEnvironment: true # Change to false if deploying anywhere but locally
```

Then in deployment.yaml:
```yaml
env:
        {{- if .Values.localDevEnvironment }}
        - name: JAVAPROTOTYPE_MYSQL_CONNECTION_STRING
          value: "jdbc:mysql://localhost:3306/java_prototype"
        {{- else }}
        - name: JAVAPROTOTYPE_MYSQL_CONNECTION_STRING
          value: {{  .Values.conn }}
        {{- end }}
```
